swagger: "2.0"
info:
  description: "Api para pedir informacion de los platos de un restaurante"
  version: "1.0.0"
  title: "Delilah Restó"
host: "localhost:3000"  
basePath: "/v1"
tags:
- name: "User"
  description: "crear, consultar, modificar o eliminar usuario"
- name: "Admin"
  description: "informacion que puede observar el administrador del sitio"
- name: "Pedido"
  description: "informacion de los pedidos"
- name: "Platos"
  description: "crear, consultar, modificar o eliminar platos"
schemes:
- "http"

paths: 
  /user/login:
    post:
      tags:
      - "User"
      summary: "Consultar usuario" 
      parameters:
      - in: "body"
        name: "body"
        description: "crear nuevo usuario"
        required: true
        schema:
          type: "object"
          properties:
            username:
              type: "string"
              description: "The user name for login"
            password:
              type: "string"
              description: "The password for login in clear text"

      responses:
        "200":
          description: "usuario encontrado con exito"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                description: "si fue exitosa o no la peticion"
              status_code:
                type: "integer"
                description: "codigo de estado"
              api_key:
                type: "object"
                description: "token de autenticacion"
              data:
                $ref: "#/definitions/User"
        "400":
          description: "no autorizado"

  /user/signUp: 
    post:
      tags: 
      - "User"
      summary: "Crear usuario"
      parameters:
      - in: "body"
        name: "body"
        description: "crear nuevo usuario"
        required: true
        schema:
          $ref: "#/definitions/newUser"
      responses:
        "200":
          description: "respuesta exitosa"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                description: "si fue exitosa o no la peticion"
              status_code:
                type: "integer"
                description: "codigo de estado"
              data:
                $ref: "#/definitions/User"
        "400":
          description: "no autorizado"
      security:
      - api_key: []
      
  /user/{username}:
    put:
      tags:
      - "User"
      summary: "modificar usuario" 
      parameters:
      - name: "username"
        in: "path"
        description: "username de usuario a modificar"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: 'datos a modificar'
        required: true
        schema:
          type: "object"
          properties:
            data:
              $ref: "#/definitions/newUser"
      responses:
        "200":
          description: "respuesta exitosa"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                description: "si fue exitosa o no la peticion"
              status_code:
                type: "integer"
                description: "codigo de estado"
              data:
                $ref: "#/definitions/User"
        "400":
          description: "no autorizado"
      security:
      - api_key: []
          
    delete:
      tags:
      - "User"
      summary: "borrar usuario"
      parameters:
      - name: "username"
        in: "path"
        description: "id del usuario"
        required: true
        type: "string"
      responses:
        "200":
          description: "respuesta exitosa"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                description: "si fue exitosa o no la peticion"
              status_code:
                type: "integer"
                description: "codigo de estado"
              data:
                $ref: "#/definitions/User"
        "400":
          description: "no autorizado"
      security:
        - api_key: []
      
  /admin:
    get:
      tags:
      - "Admin"
      summary: "Consultar pedidos" 
      responses:
        "200":
          description: "usuario encontrado con exito"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                description: "si fue exitosa o no la peticion"
              status_code:
                type: "integer"
                description: "codigo de estado"
              data:
                $ref: "#/definitions/pedidos"
        "400":
            description: "no autorizado"
      security:
        - api_key: []
                
  /admin/{id}:
    get:
      tags:
      - "Admin"
      summary: "Consultar informacion de pedido" 
      parameters:
      - name: "id"
        in: "path"
        description: "username de usuario a modificar"
        required: true
        type: "string"
      responses:
        "200":
          description: "usuario encontrado con exito"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                description: "si fue exitosa o no la peticion"
              status_code:
                type: "integer"
                description: "codigo de estado"
              data:
                $ref: "#/definitions/pedidoItem"
                
        "400":
          description: "no autorizado"
      security:
        - api_key: []
        
  /admin/status:
    put:
      tags:
      - "Admin"
      summary: "actualizar estado del pedido" 
      parameters:
      - in: "body"
        name: "body"
        description: 'datos a modificar'
        required: true
        schema:
          type: "object"
          properties:
            id:
              type: "integer"
              description: "id del pedido"
            status:
              type: "integer"
              description: "estado al cual debe ser actulizado"
      responses:
        "200":
          description: "usuario encontrado con exito"
          schema:
            type: "object"
            properties:
              status:
                type: "string"
                description: "si fue exitosa o no la peticion"
              status_code:
                type: "integer"
                description: "codigo de estado"
              data:
                $ref: "#/definitions/pedidoItem"
                
        "400":
          description: "no autorizado"
      security:
        - api_key: []
    
    
  
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
  
    
definitions:
  User:
    type: "object"
    properties:
      Username:
        type: "string"
        description: "identificador unico del usuario"
      Fullname:
        type: "string"
        description: "nombre y apellidpo del usuario"
      Email:
        type: "string"
        description: "correo del usuario"
      Phone:
        type: "string"
        description: "telefono del usuario"
      Address:
        type: "string"
        description: "direccion de envio del usuario"
      
  
  newUser:
    type: "object"
    properties:
      Username:
        type: "string"
        description: "identificador unico del usuario"
      Fullname:
        type: "string"
        description: "nombre y apellidpo del usuario"
      Email:
        type: "string"
        description: "correo del usuario"
      Phone:
        type: "string"
        description: "telefono del usuario"
      Address:
        type: "string"
        description: "direccion de envio del usuario"
      Password:
        type: "string"
        description: "contraseña del usuario"

  pedidos:
    type: "array"
    description: "lista de pedidos"
    items:
      $ref: '#/definitions/pedidoItem'
        
  pedidoItem:
    type: "object"
    properties:
      id:
        type: "integer"
        description: "id del pedido"
      status:
        type: "string"
        description: "estado del pedido"
      hour:
        type: "string"
        description: "hora pedido"
      number:
        type: "integer"
        description: "numero del pedido"
      description:
        type: "string"
        description: "detalles del pedido"
      payment:
        type: "object"
        properties:
          method:
            type: "string"
            description: "medio de pago"
          value:
            type: "integer"
            description: "dinero cancelado"
      fullname:
        type: "string"
        description: "nombre y apellidpo del usuario"
      Phone:
        type: "string"
        description: "telefono del usuario"
      address:
        type: "string"
        description: "direccion de envio del usuario"

  


    

      