openapi: 3.0.1
info:
  description: Api para pedir informacion de los platos de un restaurante
  version: 1.0.0
  title: Delilah Restó
servers:
- url: http://localhost:3000/v1/
tags:
- name: User
  description: crear, consultar, modificar o eliminar usuario



paths: 

  /user/{Username}{Password}:
    get:
      tags:
      - User
      summary: Consultar usuario 
      parameters:
      - $ref: '#/components/parameters/token'
      - name: Username
        in: path
        description: id del usuario
        schema:
          type: string
        required: true
      - name: Password
        in: path
        description: contraseña del usuario
        schema:
          type: string
        required: true
      responses:
        200:
          description: usuario encontrado con exito
          content:
            aplication/json:
              schema:
                $ref: '#/components/schemas/ResponseUserGet'
        400:
          $ref: '#/components/responses/Unauthorized'
  
  /user/new/: 
    post:
      tags: 
      - User
      summary: Crear usuario
      parameters:
      - $ref: '#/components/parameters/token'
      requestBody:
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/BodyUserPost'
        required: true
      responses:
        200:
          description: respuesta exitosa
          content:
            aplication/json:
              schema:
                $ref: '#/components/schemas/ResponseUserPost'
        400:
          $ref: '#/components/responses/Unauthorized'
    
  /user/set/:
    put:
      tags:
      - User
      summary: modificar usuario 
      parameters:
      - $ref: '#/components/parameters/token'
      requestBody:
        content:
          aplication/json:
            schema:
              $ref: '#/components/schemas/BodyUserPut'
        required: true
      responses:
        200:
          description: respuesta exitosa
          content:
            aplication/json:
              schema:
                $ref: '#/components/schemas/ResponseUserPut'
        400:
          $ref: '#/components/responses/Unauthorized'
          
  /user/delete/{Username}{Password}:
    delete:
      tags:
      - User
      summary: borrar usuario 
      parameters:
      - $ref: '#/components/parameters/token'
      - name: Username
        in: path
        description: id del usuario
        schema:
          type: string
        required: true
      - name: Password
        in: path
        description: contraseña del usuario
        schema:
          type: string
        required: true
      responses:
        200:
          description: usuario borrado con exito
          content:
            aplication/json:
              schema:
                $ref: '#/components/schemas/ResponseUserDelete'
        400:
          $ref: '#/components/responses/Unauthorized'
            
components: 
  responses:
    Unauthorized:
      description: no autorizado
  
  parameters:
    token: 
      name: token
      schema:
        type: string
      in: header
      description: token de autenticacion  
      required: true
  
  schemas:

    ResponseUserGet:
      type: object
      properties:
        status:
          type: string
          description: si fue exitosa o no la peticion
        status_code:
          type: integer
          description: codigo de estado
        data:
          type: object
          description: mensaje de respuesta con la informacion
          properties:
            Username:
              type: string
              description: identificador unico del usuario
            Fullname:
              type: string
              description: nombre y apellidpo del usuario
            Email:
              type: string
              description: correo del usuario
            Phone:
              type: string
              description: telefono del usuario
            Address:
              type: string
              description: direccion de envio del usuario
            Password:
              type: string
              description: contraseña del usuario
              
    BodyUserPost:
      type: object
      properties:
        Username:
          type: string
          description: identificador unico del usuario
        Fullname:
          type: string
          description: nombre y apellidpo del usuario
        Email:
          type: string
          description: correo del usuario
        Phone:
          type: string
          description: telefono del usuario
        Address:
          type: string
          description: direccion de envio del usuario
        Password:
          type: string
          description: contraseña del usuario
          
    ResponseUserPost:
      type: object
      properties:
        status:
          type: string
          description: si fue exitosa o no la peticion
        status_code:
          type: integer
          description: codigo de estado
        data:
          type: object
          description: mensaje de respuesta con la informacion
          properties:
            id:
              type: integer
              description: id usuario creado
    
    BodyUserPut:
      type: object
      properties:
        Username:
          type: string
          description: identificador unico del usuario
        Password:
          type: string
          description: contraseña del usuario
        data:
          type: object
          description: datos a modificar
          properties:
            Username:
              type: string
              description: identificador unico del usuario
            Fullname:
              type: string
              description: nombre y apellidpo del usuario
            Email:
              type: string
              description: correo del usuario
            Phone:
              type: string
              description: telefono del usuario
            Address:
              type: string
              description: direccion de envio del usuario
            Password:
              type: string
              description: contraseña del usuario
          
    ResponseUserPut:
      type: object
      properties:
        status:
          type: string
          description: si fue exitosa o no la peticion
        status_code:
          type: integer
          description: codigo de estado
        data:
          type: object
          description: mensaje de respuesta con la informacion
          properties:
            Username:
              type: string
              description: identificador unico del usuario
            Fullname:
              type: string
              description: nombre y apellidpo del usuario
            Email:
              type: string
              description: correo del usuario
            Phone:
              type: string
              description: telefono del usuario
            Address:
              type: string
              description: direccion de envio del usuario
            Password:
              type: string
              description: contraseña del usuario
              
    ResponseUserDelete:
      type: object
      properties:
        status:
          type: string
          description: si fue exitosa o no la peticion
        status_code:
          type: integer
          description: codigo de estado
        data:
          type: object
          description: mensaje de respuesta con la informacion
          properties:
            Username:
              type: string
              description: identificador unico del usuario
            Fullname:
              type: string
              description: nombre y apellidpo del usuario
            Email:
              type: string
              description: correo del usuario
            Phone:
              type: string
              description: telefono del usuario
            Address:
              type: string
              description: direccion de envio del usuario
            Password:
              type: string
              description: contraseña del usuario
    
    
      